### PR TITLE
Incorporate types for config

### PR DESCRIPTION
**Pull request by genebean**
This is a major rework of the module to use a type and provider instead
of a template for managing the configuration settings of a Veeam agent.
General refactoring and updating is also included.

### CODE REVIEW

**Comment by genebean** [comment]
@thespain I think a little cleanup is needed in the data files but otherwise I think its good to go... what do you think?

**Comment by genebean** [comment]
Data file clean up complete

**Comment by genebean** [comment]
@thespain any reason not to merge this? we have been using it in production for a long time.

**Comment by yachub** [comment]
@genebean Looks great, this is a major improvement to how the config is managed :) Thanks for the effort put into this, I will merge shortly and update the change log accordingly.

**Pull request merged**
